[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Jack Rothrock <jrothrock14@gmail.com>"]

# When updating/adding/removing packages, export the poetry
# changes to requirements.txt, as this is what chalice uses
# for installing 3rd party libraries.

[tool.poetry.dependencies]
python = "^3.10"
chalice = "^1.29.0"
boto3 = "^1.28.15"
requests = "^2.31.0"
pynamodb = "^5.5.0"
taskipy = "^1.12.0"

[tool.poetry.dev-dependencies]
black = "^22.1"
pydocstyle = "^6.1"
pytest = "^6.2"
toml = "^0.10"
pytest-env = "^0.6.2"
mypy = "^0.950"
isort = "^5.12.0"
flake8 = "^6.0.0"

[tool.black]
exclude = ".venv"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
no_site_packages = true
explicit_package_bases = true
namespace_packages = true

[tool.isort]
profile = "black"
skip_glob = [".venv/*"]
quiet = true
force_single_line = true

[tool.pydocstyle]
match-dir='[^\.venv].*'

[tool.taskipy.tasks]
black = "black ."
isort = "isort ."
flake8 = "flake8 ."
mypy = "mypy ."
pydoc = "pydocstyle .  --count"
lint = "poetry run task flake8 && poetry run task mypy && poetry run task pydoc"
format = "poetry run task black && poetry run task isort"
verify = "poetry run task lint && poetry run task format"
export = "poetry export -f requirements.txt --output requirements.txt" 
deploy = "poetry run task export && chalice deploy"
dev = "chalice local"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
